### ISSUE TITLE
I can not log in to Web Console.

### ISSUE THREAD

**Issue by golgoru** [PaloAltoNetworks/googlecloud#4]
in PDF document, it shows me that ID : paloalto and PW : Pal0Alt0@123.

but when I try log in process, I can see the message such as "invalid username or password"

can U help me ?

**Comment by golgoru** [comment]
I solved it. there is some mis spell in bucket folder name.
after edit folder name correctly, I can log in. thank you.

**Comment by ghost** [comment]
Hello, I have exactly the same problem. What is the relevant file and parameter please ?

**Comment by golgoru** [comment]
It's old and I can't remember it, but I remember that there was an error
because I didn't follow the guide in the explanation document.
Please check the file name or folder name again.

I hope it helps.

2020년 10월 20일 (화) 오후 4:02, zorions <notifications@github.com>님이 작성:

**Comment by ghost** [comment]
Ok thanks.
